# Site settings
baseurl = "/" #without ending slash
languageCode = "en-us"
#defaultContentLanguage = "en"
theme = "identity-learn"
themesDir = "themes"
metaDataFormat = "yaml"
#defaultContentLanguageInSubdir= true
#googleAnalytics = "UA-XXXXX-Y"
disqusShortname = "bpharm"
#disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

[params]
  editURL = "https://github.com/jasminerimal/jasminerimal.github.io/edit/deploy/content/"
  uploadURL = "https://github.com/jasminerimal/jasminerimal.github.io/upload/master/content/"
  description = "Jasmine's Website"
  repoView = "https://github.com/jasminerimal/jasminerimal.github.io"
  repoStar = "https://github.com/jasminerimal/jasminerimal.github.io"
  repoFork = "https://github.com/jasminerimal/jasminerimal.github.io/fork"
  author = "Jasmine Rimal"
  disableBreadcrumb = false
  disableNextPrev = false
  showVisitedLinks = true
  disableLanguageSwitchingButton = true
  siteTitle = "Jasmine Rimal"
  sbaseurl = "https://jasminerimal.com.np" #to replace BaseURL instances for subpage shortcodes

[outputs]
    home = [ "HTML", "RSS", "JSON"] 

##IdentityParams
  [params.personal]
    name = "Jasmine Rimal"
    avatar = "jas.png"
    position = "Medical Student"
    livesIn = "[Lalitpur, Nepal](#https://www.google.com.np/maps/place/Thasikhel,+Patan)"
    scope = [
        "Studies [B.Pharm](http://nobelcollege.edu.np/Sites/Public/Programs/Science/BPharm.aspx)",
        "Lives to [Dance](https://www.youtube.com/watch?v=dQw4w9WgXcQ)",
        "[AVM](https://en.wikipedia.org/wiki/Adarsha_Vidya_Mandir)ite and [DAV](http://www.davcollege.edu.np/)ian"
      ]
    biography = """Jasmine Rimal is a simple girl, enjoying the simple things in life. With a passion for pharmacy, this medical student takes interest in health science pertaining to safe medical dispensation"""

  [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "your@email.com"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://example.com/mailout/"

    enable = false
    title = "Want to ask me something specific?"
    namePlaceholder = "Name"
    emailPlaceholder = "Email"
    messagePlaceholder = "Message"
    buttonText = "Send it"
    success = "Thank you for contacting us."
    error = "Message could not be send. Please contact us at "

    # Google invisible captcha
      #[params.contact.captcha]
      #  sitekey = ""


      # Add optional form fields to identify contact forms.
      #[[params.contact.fields.hidden]]
      #  name = "someID"
      #  value = "example.com"

      #[[params.contact.fields.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Social settings
    [[params.social]]
      title = "Github"
      icon = "fa-github"
      link = "https://github.com/jasminerimal/"
      target = "_blank"

    [[params.social]]
      title = "Instagram"
      icon = "fa-instagram"
      link = "https://www.instagram.com/jasmine_rimal/"
      target = "_blank"

    [[params.social]]
      title = "Facebook"
      icon = "fa-facebook"
      link = "https://www.facebook.com/JasmineRimal/"
      target = "_blank"

    [[params.social]]
      title = "Bpharm"
      icon = "fa-book"
      # icon = "fa-medkit"
      link = "/bpharm"
      #target = "_blank"

# Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Jasmine Rimal"

  # Page license
  [params.license]
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    # Title is used as URL text
    title = "Github"
    # Text will be used to explain the credit
    text = "Powered by"
    link = "https://github.com/jasminerimal/jasminerimal.github.io"

  # Optional piwik tracking
    #[params.analytics.piwik]
    #  URL = "https://stats.example.com"
    #  ID = "42"
    #  # Track all subdomains with "*.example.com"
    #  domain = "www.example.com"
    #  # Optional integrity check hash
    #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

[Languages]

  [Languages.en]
  title = "Home"
  weight = 1
  languageName = "English"

  [[Languages.en.menu.shortcuts]]
  name = "<i class='fa fa-home'></i> Homepage"
  url = "../.."
  weight = 20

  [[Languages.en.menu.shortcuts]]
  name = "<i class='fa fa-code-branch'></i> Contribute"
  url = "how-to-contribute"
  weight = 30

  [[Languages.en.menu.shortcuts]]
  name = "<i class='fa fa-bullhorn'></i> Credits"
  url = "credits"
  weight = 40

  [[Languages.en.menu.shortcuts]]
  name = "<i class='fa fa-file-signature'></i> Disclaimer"
  url = "disclaimer"
  weight = 50